---
abstract: 'Catalyst::Controller::REST with CRUD'
author:
  - 'Peter Karman, C<< <karman at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-CRUD-Controller-REST
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::REST: 0
  Catalyst::Plugin::Static::Simple: 0
  CatalystX::CRUD: 0.54
  JSON: 2
  Scalar::Util: 0
  Test::More: 0
  perl: 5.8.3
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CatalystX-CRUD-Controller-REST
  homepage: https://github.com/karpet/catalystx-crud-controller-rest
  license: http://dev.perl.org/licenses/
  repository: https://github.com/karpet/catalystx-crud-controller-rest.git
version: '0.005'
